derave1577 - 2/26/2026

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, f1_score, precision_score, recall_score

student_id = "derave1577"
file_path = "C:\\Users\\Student\\Downloads\\Stroke_Prediction_Dataset.xlsx"

df = pd.read_excel(file_path)

categorical_cols = ['Gender', 'Marital Status', 'Work Type', 'Residence Type', 'Smoking Status', 'Alcohol Intake', 'Physical Activity', 'Family History of Stroke', 'Dietary Habits', 'Diagnosis']

df_encoded = pd.get_dummies(df, columns=categorical_cols, dtype=int)
display(df_encoded.head())
print(df_encoded.columns)

,Patient ID,Patient Name,Age,Hypertension,Heart Disease,Average Glucose Level,Body Mass Index (BMI),Stroke History,Stress Levels,Systolic Blood Pressure,...,Family History of Stroke_Yes,Dietary Habits_Gluten-Free,Dietary Habits_Keto,Dietary Habits_Non-Vegetarian,Dietary Habits_Paleo,Dietary Habits_Pescatarian,Dietary Habits_Vegan,Dietary Habits_Vegetarian,Diagnosis_No Stroke,Diagnosis_Stroke
0,18153,Mamooty Khurana,56,0,1,130.91,22.37,0,3.48,140,...,1,0,0,0,0,0,1,0,0,1
1,62749,Kaira Subramaniam,80,0,0,183.73,32.57,0,1.73,146,...,0,0,0,0,1,0,0,0,0,1
2,32145,Dhanush Balan,26,1,1,189.00,20.32,0,7.31,154,...,1,0,0,0,1,0,0,0,0,1
3,6154,Ivana Baral,73,0,0,185.29,27.50,0,5.35,174,...,0,0,0,0,1,0,0,0,1,0
4,48973,Darshit Jayaraman,51,1,1,177.34,29.06,0,6.84,121,...,1,0,0,0,0,1,0,0,0,1

Index(['Patient ID', 'Patient Name', 'Age', 'Hypertension', 'Heart Disease',
       'Average Glucose Level', 'Body Mass Index (BMI)', 'Stroke History',
       'Stress Levels', 'Systolic Blood Pressure', 'Diastolic Blood Pressure',
       'HDL Cholesterol', 'LDL Cholesterol', 'Not Reported', 'Blurred Vision',
       'Dizziness', 'Seizures', 'Weakness', 'Severe Fatigue', 'Headache',
       'Confusion', 'Difficulty Speaking', 'Numbness', 'Loss of Balance',
       'Gender_Female', 'Gender_Male', 'Marital Status_Divorced',
       'Marital Status_Married', 'Marital Status_Single',
       'Work Type_Government Job', 'Work Type_Never Worked',
       'Work Type_Private', 'Work Type_Self-employed', 'Residence Type_Rural',
       'Residence Type_Urban', 'Smoking Status_Currently Smokes',
       'Smoking Status_Formerly Smoked', 'Smoking Status_Non-smoker',
       'Alcohol Intake_Frequent Drinker', 'Alcohol Intake_Never',
       'Alcohol Intake_Rarely', 'Alcohol Intake_Social Drinker',
       'Physical Activity_High', 'Physical Activity_Low',
       'Physical Activity_Moderate', 'Family History of Stroke_No',
       'Family History of Stroke_Yes', 'Dietary Habits_Gluten-Free',
       'Dietary Habits_Keto', 'Dietary Habits_Non-Vegetarian',
       'Dietary Habits_Paleo', 'Dietary Habits_Pescatarian',
       'Dietary Habits_Vegan', 'Dietary Habits_Vegetarian',
       'Diagnosis_No Stroke', 'Diagnosis_Stroke'],
      dtype='str')

In [2]:
X_class = df_encoded[['Age', 'Work Type_Self-employed', 'Work Type_Government Job', 'Work Type_Private', 'Work Type_Never Worked', 'Body Mass Index (BMI)', 'Average Glucose Level']]
y_class = df_encoded['Diagnosis_Stroke']

X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(X_class, y_class, test_size=0.2, random_state=42)

In [3]:
linear_model = LinearRegression()
logistic_model = LogisticRegression(random_state=42)

linear_model.fit(X_train_class, y_train_class)
logistic_model.fit(X_train_class, y_train_class)

y_pred_linear = linear_model.predict(X_test_class)
y_pred_logistic = logistic_model.predict(X_test_class)

accuracy = accuracy_score(y_train_class, logistic_model.predict(X_train_class))

X_test_class['Predicted_Logistic'] = y_pred_logistic
accuracy_logistic = accuracy_score(y_test_class, y_pred_logistic)
f1 = f1_score(y_test_class, y_pred_logistic, average='weighted')
precision = precision_score(y_test_class, y_pred_logistic)
recall = recall_score(y_test_class, y_pred_logistic)

mae = mean_absolute_error(y_train_class, linear_model.predict(X_train_class))
mse = mean_squared_error(y_train_class, linear_model.predict(X_train_class))
r2 = r2_score(y_train_class, linear_model.predict(X_train_class))

display(f'Accuracy: {accuracy_logistic}')
display(f'Precision: {precision}')
display(f'Recall: {recall}')
display(f'F1 Score: {f1}')

display(f'MAE: {mae}')
display(f'MSE: {mse}')
display(f'R2 Score: {r2}')

'Accuracy: 0.502'

'Precision: 0.511520737327189'

'Recall: 0.36537195523370636'

'F1 Score: 0.492321554770318'

'MAE: 0.4996125107770145'

'MSE: 0.2498062553885073'

'R2 Score: 0.0007027792217694229'

In [4]:
coefficient_df = pd.DataFrame({
    'Feature': X_class.columns,
    'Coefficient': linear_model.coef_.ravel()
})

coefficient_df = coefficient_df.sort_values(by='Coefficient', ascending=False)

display(coefficient_df)

                    Feature  Coefficient
1   Work Type_Self-employed     0.015181
6     Average Glucose Level     0.000204
0                       Age    -0.000026
5     Body Mass Index (BMI)    -0.000554
3         Work Type_Private    -0.001417
2  Work Type_Government Job    -0.003421
4    Work Type_Never Worked    -0.010343